name: Fetch CF preferred IPs

on:
  schedule:
    - cron: "17 */2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python3 cf_fetch.py
        env:
          GIST_ID: "${{ secrets.GIST_ID }}"
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
